Add python build-dep to prevent conflict
Without this we get:

Error: The following specifications were found to be in conflict:
  - msinttypes -> feature:vc9
  - posix
Use "conda info <package>" to see the dependencies for each package

.. because nothing in the build env. provides that feature.